name: Income Boss
favicon: null
layout_spectrum: 0.25925
typography_spectrum: 0.88786
title: Income Boss
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75791708-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1c24'
    - '#c000c2'
    - '#000000'
    - '#ead9eb'
    - '#a46ba8'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
