analytics:
  google: UA-75791708-2
color:
  brandColors:
    - '#ed1c24'
    - '#c000c2'
    - '#000000'
    - '#ead9eb'
    - '#a46ba8'
  brandStrength: 0.1875
  lightness: 0.875
  rhythmicContrast: 0.75
  saturation: 0.4375
cta: {}
layout_spectrum: 0.352477
name: Income Boss
opengraph: {}
purpose: []
typography_spectrum: 0.88786
