name: partytentclub
favicon: null
layout_spectrum: 0.21347742341458797
typography_spectrum: 0.8770239211153239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6240251595154405
  lightness: 0.3838571247179061
  saturation: 0.9889409078750759
  rhythmicContrast: 0.6465242435224354
purpose: []
